---
name: Pages Build and Deploy

#
# This workflow for building and deploying a Jekyll site to GitHub Pages.
#
# Inspired by:
# https://github.com/actions/jekyll-build-pages
#

on:
  release:
    types: [published]

permissions: {}

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: false

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Build and Run
        run: |
          bash ./.github/scripts/build.sh
          echo "artifact=docs/_data/pages/${FIST_ARTIFACT}#STIX Bundle" >> "$GITHUB_ENV"
          echo "source=docs" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          FIST_BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          FIST_OUTPUT_DIR: out
          FIST_ARTIFACT: ${{ vars.FIST_ARTIFACT || 'bundle.json' }}
          LANGUAGE: ${{ vars.LANGUAGE }}

      - name: Upload Release Artifact
        run: gh release upload "${{ github.event.release.tag_name }}" "$artifact" --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build with Jekyll
        run: |
          sed -i "s|^url:.*|url: \"${{ steps.pages.outputs.base_url }}\"|" "$source/_config.yml"
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --source "$source"
        env:
          JEKYLL_ENV: production
          FIST_ARTIFACT: ${{ vars.FIST_ARTIFACT || 'bundle.json' }}
          LANGUAGE: ${{ vars.LANGUAGE }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
